### ISSUE TITLE
/usr/bin/python3: No module named bin.train

### ISSUE THREAD

**Issue by SeekPoint** [sld/reverse-squad#2]
mldl@mldlUB1604:~/ub16_prj/reverse-squad$ bash bin/seq2seq_with_att
/usr/bin/python3: No module named bin.train

**Comment by Embedding** [comment]
I really like this project but I met the same problem.

**Comment by sld** [comment]
This repo uses seq2seq fork: https://github.com/google/seq2seq
It placed in seq2seq folder.

Try to 
```
cd seq2seq
# Install package and dependencies
pip install -e .
```

**Comment by SeekPoint** [comment]
but there is not 'train' in bin directory

**Comment by sld** [comment]
`bin.train` is the part of google/seq2seq.

After `pip install -e .` the `python -m "bin.train"` should work.

**Comment by SeekPoint** [comment]
it works after add 
PYTHONPATH=seq2seq

**Comment by SeekPoint** [comment]
it works after add 
PYTHONPATH=seq2seq
